language: "python"
python:
    - "3.4"
cache: "pip"
install:
    - "pip install .[tests]"
script:
    - "pytest"
after_success:
    - "coveralls"
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.4"
        repo: "pyvec/python.cz"
