language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -r requirements.txt"
script: "py.test"

deploy:
    provider: "heroku"
    api_key:
        secure: "k6MrvzAG8doCYdS0ncp9FRrX+05aspgLFMWwUJUkt80AINUk9WXWwf/sIeCBZ1OQd3JejqAScM/PR5FQJ2ShLJMbDUSmHgrZoLD5cG+FIDkfhBMv3LAZ1Co3h6oXQq9RaavlXeYRRheLFm4QaNMoRFu9ug/LbyE9m22P0Q01Vzk="
    app: "pythoncz"
    on:
        branch: "master"
        python: "3.4"
        repo: honzajavorek/python.cz
