language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -r requirements.txt"
script:
    - "flake8 ."
    - "py.test"

deploy:
    provider: "heroku"
    api_key:
        secure: "TkF6T+X2vU+18X2/ERSvg056SIaCT+JjpcjXfC4Fwc1Fx07VYNAiD0m6ZEucpq9L9uUUqXXgcsLqwYoei9PBPGOd2CrEilw56zwWFwA7JKm3FvKw2gDrxDE/ckmLU+F8hgJle06A6cbGhx+MbsrVz7EeQ/njwLRlPYJW2Xtnzqw="
    app: "pythoncz"
    on:
        branch: "master"
        python: "3.4"
        repo: honzajavorek/python.cz
