language: "python"
python:
    - "3.4"
cache: "pip"
install:
    - "pip install ."
script:
    - "flake8 ."
    - "py.test pythoncz_tests"
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.4"
        repo: "pyvec/python.cz"
