version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project
  python-node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/project

jobs:
  install_and_test:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pipenv install --dev
      - persist_to_workspace:
          root: "~"
          paths:
              - .local/share/virtualenvs
              - project
      - run:
          name: run tests
          command: pipenv run test
      - run:
          name: send coverage report
          command: pipenv run codecov

  build_articles:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run build articles
      - persist_to_workspace:
          root: "~"
          paths:
              - project/pythoncz/pages/articles/*_data.json

  build_events:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run build events
      - persist_to_workspace:
          root: "~"
          paths:
              - project/pythoncz/pages/events/*_data.json

  build_web:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run build web
      - persist_to_workspace:
          root: "~"
          paths:
              - project/build

  deploy:
    executor: python-node
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: install 'now'
          command: sudo npm install --global --unsafe-perm now
      - run:
          # $NOW_TOKEN needs to be set
          name: deploy
          command: pipenv run deploy "$CIRCLE_BRANCH"

workflows:
  version: 2
  default_workflow: &default_workflow
    jobs:
      - install_and_test
      - build_articles:
          requires:
            - install_and_test
      - build_events:
          requires:
            - install_and_test
      - build_web:
          requires:
            - build_articles
            - build_events
      - deploy:
          requires:
            - build_web
          filters:
            branches:
              only:
                - master
  nightly_workflow:
    <<: *default_workflow
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
