version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project
  node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/project

jobs:
  install:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pipenv install --dev
      - persist_to_workspace:
          root: "~"
          paths:
              - .local/share/virtualenvs
              - project

  test:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: run tests
          command: pipenv run test
      - run:
          # $CODECOV_TOKEN needs to be set
          name: send coverage report
          command: pipenv run codecov

  build_events:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run build events
      - persist_to_workspace:
          root: "~"
          paths:
              - project/data/events

  build_web:
    executor: python
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run build web
      - persist_to_workspace:
          root: "~"
          paths:
              - project/web/build

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: install 'now'
          command: sudo npm install --global --unsafe-perm now
      - run:
          # $NOW_TOKEN needs to be set
          command: pipenv run deploy "$CIRCLE_BRANCH"

workflows:
  version: 2
  default_workflow: &default_workflow
    jobs:
      - install
      - test:
          requires:
            - install
      - build_events:
          requires:
            - test
      - build_web:
          requires:
            - build_events
      - deploy:
          requires:
            - build_web
  nightly_workflow:
    <<: *default_workflow
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
