version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pipenv install --dev
      - run:
          name: run tests
          command: pipenv run test
      - run:
          name: send coverage report
          command: pipenv run codecov
