feeds:
  - name: Pyvo
    url: https://pyvo.cz/
    ics_url: https://pyvo.cz/api/pyvo.ics
  - name: PyWorking
    url: https://pyworking.cz/
    ics_url: https://pyworking.cz/workshops.ics
  - name: PyWorking Sessions
    url: https://pyworking.cz/
    ics_url: http://api.meetup.com/pyworking/upcoming.ical
  - name: PyData Prague
    url: https://www.meetup.com/PyData-Prague/
    ics_url: http://api.meetup.com/PyData-Prague/upcoming.ical
  - name: Czech Python Events
    url: https://calendar.google.com/calendar/embed?src=kfdeelic1a13jsp7jvai861vfs%40group.calendar.google.com&ctz=Europe%2FPrague
    ics_url: https://calendar.google.com/calendar/ical/kfdeelic1a13jsp7jvai861vfs%40group.calendar.google.com/public/basic.ics
